# Dọn dữ liệu có sẵn của thư mục BM3

## Tham khảo file preprocessing_v2\image\FilterData2014.ipynb, để có file df_meta_5core_2014.parquet

In [ ]:
# %pip install pyarrow

Collecting pyarrow
  Using cached pyarrow-23.0.1-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Downloading pyarrow-23.0.1-cp312-cp312-win_amd64.whl (27.6 MB)
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   - -------------------------------------- 0.8/27.6 MB 8.3 MB/s eta 0:00:04
   ----------- ---------------------------- 8.1/27.6 MB 31.5 MB/s eta 0:00:01
   --------------------- ------------------ 14.7/27.6 MB 29.7 MB/s eta 0:00:01
   ----------------------------- ---------- 20.2/27.6 MB 28.3 MB/s eta 0:00:01
   ---------------------------------- ----- 24.1/27.6 MB 26.8 MB/s eta 0:00:01
   ---------------------------------------  27.0/27.6 MB 24.8 MB/s eta 0:00:01
   ---------------------------------------- 27.6/27.6 MB 21.9 MB/s  0:00:01
Installing collected packages: pyarrow
Successfully installed pyarrow-23.0.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import pandas as pd

In [3]:
PATH = "../data/baby/2014"

In [44]:
os.makedirs(os.path.join(PATH, "step0_clean_data"), exist_ok=True)

In [42]:
df_meta = pd.read_parquet(os.path.join(PATH, "df_meta_5core_2014.parquet"))

In [34]:
df_meta.info()

<class 'pandas.DataFrame'>
Index: 7050 entries, 7 to 71289
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   asin         7050 non-null   str
 1   categories   7050 non-null   object
 2   description  6956 non-null   str
 3   title        7037 non-null   str
 4   price        6883 non-null   float64
 5   imUrl        7037 non-null   str
 6   brand        4926 non-null   str
 7   related      6946 non-null   object
 8   salesRank    4 non-null      object
dtypes: float64(1), object(3), str(5)
memory usage: 4.9+ MB

In [35]:
df_meta.head(3)

,asin,categories,description,title,price,imUrl,brand,related,salesRank
7,097293751X,[[Baby]],Easily keep track of your baby's or child's da...,"Baby Tracker&reg; - Daily Childcare Journal, S...",17.00,http://ecx.images-amazon.com/images/I/41Bb6wf%...,Time Too,"{'also_bought': ['9729375011', 'B004FN1AE8', '...",None
108,9729375011,[[Baby]],This is version of the award-winningBaby Track...,Newborn Baby Tracker&reg; - Round the Clock Ch...,15.95,http://ecx.images-amazon.com/images/I/51r3BLpL...,NaN,"{'also_bought': ['B000V5KPZ4', 'B001F8TLLU', '...",None
134,B00000IZQI,[[Baby]],This colorful car collection develops motor sk...,Fisher Price Nesting Action Vehicles,8.37,http://ecx.images-amazon.com/images/I/51E83QCC...,NaN,"{'also_bought': ['B0042D69W4', 'B00428LIZM', '...",None

In [36]:
df_meta_to_drop = df_meta[df_meta["imUrl"].isna()].copy()
df_meta_to_drop.shape

(13, 9)

In [41]:
# Bỏ các dòng bị thiếu ảnh
df_meta.dropna(subset=["imUrl"], inplace=True)

In [38]:
df_meta.shape

(7037, 9)

In [46]:
df_meta.info()

<class 'pandas.DataFrame'>
Index: 7050 entries, 7 to 71289
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   asin         7050 non-null   str
 1   categories   7050 non-null   object
 2   description  6956 non-null   str
 3   title        7037 non-null   str
 4   price        6883 non-null   float64
 5   imUrl        7037 non-null   str
 6   brand        4926 non-null   str
 7   related      6946 non-null   object
 8   salesRank    4 non-null      object
dtypes: float64(1), object(3), str(5)
memory usage: 4.9+ MB

In [45]:
## Ghi ra lại file
df_meta.to_parquet(
    os.path.join(PATH, "step0_clean_data", "df_meta.parquet"), index=False
)

## Lọc file csv bỏ mấy dòng không hình

In [10]:
df_rating_5core = pd.read_csv(
    os.path.join(PATH, "ratings_Baby_5core.csv"),
    names=["userID", "itemID", "rating", "timestamp"],
    header=None,
)

In [11]:
df_rating_5core.info()

<class 'pandas.DataFrame'>
RangeIndex: 160792 entries, 0 to 160791
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userID     160792 non-null  str
 1   itemID     160792 non-null  str
 2   rating     160792 non-null  float64
 3   timestamp  160792 non-null  int64
dtypes: float64(1), int64(1), str(2)
memory usage: 8.5 MB

In [12]:
df_rating_5core.head(3)

           userID      itemID  rating   timestamp
0  A1HK2FQW6KXQB2  097293751X     5.0  1373932800
1  A19K65VY14D13R  097293751X     5.0  1372464000
2  A2LL1TGG90977E  097293751X     5.0  1395187200

In [13]:
# df_rating_5core.to_parquet(os.path.join(PATH, "df_rating.parquet"), index=False)

In [14]:
## Bỏ các dòng có asin trong df_meta_to_drop
# df_rating = df_rating_5core[
#     ~df_rating_5core["itemID"].isin(set(df_meta_to_drop["asin"]))
# ].copy()
df_rating = df_rating_5core.copy()

In [15]:
df_rating.info()

<class 'pandas.DataFrame'>
RangeIndex: 160792 entries, 0 to 160791
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userID     160792 non-null  str
 1   itemID     160792 non-null  str
 2   rating     160792 non-null  float64
 3   timestamp  160792 non-null  int64
dtypes: float64(1), int64(1), str(2)
memory usage: 8.5 MB

In [16]:
160792 - 160522

270

In [17]:
df_rating.to_parquet(
    os.path.join(PATH, "step0_clean_data", "df_rating.parquet"), index=False
)